### ISSUE TITLE
Disable the maximize window button

### ISSUE THREAD

**Issue by rmariuzzo** [raydelto/srtsynch#1]
I think it doesn't make sense to have a maximize window button, see the following screenshot: 
![screenshot from 2015-02-08 11 32 24](https://cloud.githubusercontent.com/assets/439839/6097116/76d683cc-af86-11e4-957d-3ae8016c2ab4.png)

**Comment by raydelto** [comment]
Issue fixed with commit 6cb3345177ec98fa2d5a62ba989a0bea9b760994

**Comment by rmariuzzo** [comment]
That was quick!
