### ISSUE TITLE
You can put the preview of photo example directly in the markdown

### ISSUE THREAD

**Issue by rafaelmedian** [raydelto/srtsynch#2]
You can see a screenshot of this simple app:
`![Example 1](url to image)`
![Example 2](http://www.raydelto.org/screen_shots/srt_synch.png)

**Comment by rmariuzzo** [comment]
I agree, that would be nice. Also you can include the same screenshot from different OS.

![screenshot from 2015-02-08 11 32 10](https://cloud.githubusercontent.com/assets/439839/6097152/359a1fca-af88-11e4-9fe2-92277073dd07.png)

**Comment by raydelto** [comment]
Excellent recommendation.   I have added both Windows and Ubuntu screenshots directly to the README.MD file. Thank you very much!
